server:
  port: ${PORT:8081}

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product_db
    username: ${USER_DB}
    password: ${PASSWORD_DB}
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show_sql: true

    rabbitmq:
      host: ${RABBIT_MQ_HOST:localhost}
      port: ${RABBIT_MQ_PORT:5672}
      username: ${RABBIT_MQ_USER}
      password: ${RABBIT_MQ_PASSWORD}

app-config:
  services:
    sale: http://${SALES_HOST:localhost}:${SALES_PORT:8082}

  secrets:
    api-secret: ${API_SECRET}

  rabbit:
    exchange:
      product: product.topic

    routingKey:
      product-stock: product-stock-update.routingKey
      sales-confirmation: sales-confirmation.routingKey

    queue:
      product-stock: product-stock-update.queue
      sales-confirmation: sales-confirmation.queue